version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Africa/Nairobi"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "composer"
    groups:
      symfony:
        applies-to: version-updates
        patterns:
          - "symfony/*"
          - "symfony-cmf/*"
          - "symfonycasts/*"
        update-types:
          - "minor"
          - "patch"
      doctrine:
        applies-to: version-updates
        patterns:
          - "doctrine/*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Africa/Nairobi"
    commit-message:
      prefix: "ci"
